export const tribunals = [
  { name: "Agen", type: "Tribunal de commerce" },
  { name: "Aire-sur-l'Adour", type: "Tribunal de commerce" },
  { name: "Ajaccio", type: "Tribunal de commerce" },
  { name: "Albi", type: "Tribunal de commerce" },
  { name: "Alençon", type: "Tribunal de commerce" },
  { name: "Amiens", type: "Tribunal de commerce" },
  { name: "Angers", type: "Tribunal de commerce" },
  { name: "Angoulême", type: "Tribunal de commerce" },
  { name: "Annecy", type: "Tribunal de commerce" },
  { name: "Annonay", type: "Tribunal de commerce" },
  { name: "Antibes", type: "Tribunal de commerce" },
  { name: "Apt", type: "Tribunal de commerce" },
  { name: "Arras", type: "Tribunal de commerce" },
  { name: "Aubenas", type: "Tribunal de commerce" },
  { name: "Auch", type: "Tribunal de commerce" },
  { name: "Aurillac", type: "Tribunal de commerce" },
  { name: "Auxerre", type: "Tribunal de commerce" },
  { name: "Avignon", type: "Tribunal de commerce" },
  { name: "Bar-le-Duc", type: "Tribunal de commerce" },
  { name: "Bastia", type: "Tribunal de commerce" },
  { name: "Bayonne", type: "Tribunal de commerce" },
  { name: "Beauvais", type: "Tribunal de commerce" },
  { name: "Belfort", type: "Tribunal de commerce" },
  { name: "Bergerac", type: "Tribunal de commerce" },
  { name: "Bernay", type: "Tribunal de commerce" },
  { name: "Besançon", type: "Tribunal de commerce" },
  { name: "Béziers", type: "Tribunal de commerce" },
  { name: "Blois", type: "Tribunal de commerce" },
  { name: "Bobigny", type: "Tribunal de commerce" },
  { name: "Bordeaux", type: "Tribunal de commerce" },
  { name: "Boulogne-sur-Mer", type: "Tribunal de commerce" },
  { name: "Bourg-en-Bresse", type: "Tribunal de commerce" },
  { name: "Bourges", type: "Tribunal de commerce" },
  { name: "Brest", type: "Tribunal de commerce" },
  { name: "Briey", type: "Tribunal de commerce" },
  { name: "Brive-la-Gaillarde", type: "Tribunal de commerce" },
  { name: "Caen", type: "Tribunal de commerce" },
  { name: "Cahors", type: "Tribunal de commerce" },
  { name: "Cannes", type: "Tribunal de commerce" },
  { name: "Carcassonne", type: "Tribunal de commerce" },
  { name: "Castres", type: "Tribunal de commerce" },
  { name: "Chalon-sur-Saône", type: "Tribunal de commerce" },
  { name: "Châlons-en-Champagne", type: "Tribunal de commerce" },
  { name: "Chambéry", type: "Tribunal de commerce" },
  { name: "Chartres", type: "Tribunal de commerce" },
  { name: "Châteauroux", type: "Tribunal de commerce" },
  { name: "Chaumont", type: "Tribunal de commerce" },
  { name: "Cherbourg", type: "Tribunal de commerce" },
  { name: "Clermont-Ferrand", type: "Tribunal de commerce" },
  { name: "Compiègne", type: "Tribunal de commerce" },
  { name: "Coutances", type: "Tribunal de commerce" },
  { name: "Créteil", type: "Tribunal de commerce" },
  { name: "Dax", type: "Tribunal de commerce" },
  { name: "Dieppe", type: "Tribunal de commerce" },
  { name: "Dijon", type: "Tribunal de commerce" },
  { name: "Douai", type: "Tribunal de commerce" },
  { name: "Draguignan", type: "Tribunal de commerce" },
  { name: "Dunkerque", type: "Tribunal de commerce" },
  { name: "Épinal", type: "Tribunal de commerce" },
  { name: "Évreux", type: "Tribunal de commerce" },
  { name: "Évry", type: "Tribunal de commerce" },
  { name: "Foix", type: "Tribunal de commerce" },
  { name: "Fort-de-France", type: "Tribunal mixte de commerce (DOM-TOM)" },
  { name: "Fréjus", type: "Tribunal de commerce" },
  { name: "Grasse", type: "Tribunal de commerce" },
  { name: "Grenoble", type: "Tribunal de commerce" },
  { name: "Guéret", type: "Tribunal de commerce" },
  { name: "Le Havre", type: "Tribunal de commerce" },
  { name: "Le Mans", type: "Tribunal de commerce" },
  { name: "Le Puy-en-Velay", type: "Tribunal de commerce" },
  { name: "La Roche-sur-Yon", type: "Tribunal de commerce" },
  { name: "La Rochelle", type: "Tribunal de commerce" },
  { name: "Laval", type: "Tribunal de commerce" },
  { name: "Libourne", type: "Tribunal de commerce" },
  { name: "Lille Métropole", type: "Tribunal de commerce" },
  { name: "Limoges", type: "Tribunal de commerce" },
  { name: "Lisieux", type: "Tribunal de commerce" },
  { name: "Lons-le-Saunier", type: "Tribunal de commerce" },
  { name: "Lorient", type: "Tribunal de commerce" },
  { name: "Lyon", type: "Tribunal de commerce" },
  { name: "Mâcon", type: "Tribunal de commerce" },
  { name: "Mamoudzou", type: "Tribunal mixte de commerce (DOM-TOM)" },
  { name: "Manosque", type: "Tribunal de commerce" },
  { name: "Marseille", type: "Tribunal de commerce" },
  { name: "Meaux", type: "Tribunal de commerce" },
  { name: "Melun", type: "Tribunal de commerce" },
  { name: "Mende", type: "Tribunal de commerce" },
  { name: "Metz", type: "Tribunal judiciaire statuant commercialement (Alsace-Moselle)" },
  { name: "Mont-de-Marsan", type: "Tribunal de commerce" },
  { name: "Montauban", type: "Tribunal de commerce" },
  { name: "Montluçon", type: "Tribunal de commerce" },
  { name: "Montpellier", type: "Tribunal de commerce" },
  { name: "Mulhouse", type: "Tribunal judiciaire statuant commercialement (Alsace-Moselle)" },
  { name: "Nancy", type: "Tribunal de commerce" },
  { name: "Nanterre", type: "Tribunal de commerce" },
  { name: "Nantes", type: "Tribunal de commerce" },
  { name: "Narbonne", type: "Tribunal de commerce" },
  { name: "Nevers", type: "Tribunal de commerce" },
  { name: "Nice", type: "Tribunal de commerce" },
  { name: "Nîmes", type: "Tribunal de commerce" },
  { name: "Niort", type: "Tribunal de commerce" },
  { name: "Nouméa", type: "Tribunal mixte de commerce (DOM-TOM)" },
  { name: "Orléans", type: "Tribunal de commerce" },
  { name: "Papeete", type: "Tribunal mixte de commerce (DOM-TOM)" },
  { name: "Paris", type: "Tribunal de commerce" },
  { name: "Pau", type: "Tribunal de commerce" },
  { name: "Périgueux", type: "Tribunal de commerce" },
  { name: "Perpignan", type: "Tribunal de commerce" },
  { name: "Pointe-à-Pitre", type: "Tribunal mixte de commerce (DOM-TOM)" },
  { name: "Poitiers", type: "Tribunal de commerce" },
  { name: "Pontoise", type: "Tribunal de commerce" },
  { name: "Quimper", type: "Tribunal de commerce" },
  { name: "Reims", type: "Tribunal de commerce" },
  { name: "Rennes", type: "Tribunal de commerce" },
  { name: "Roanne", type: "Tribunal de commerce" },
  { name: "Rodez", type: "Tribunal de commerce" },
  { name: "Romans-sur-Isère", type: "Tribunal de commerce" },
  { name: "Rouen", type: "Tribunal de commerce" },
  { name: "Saint-Brieuc", type: "Tribunal de commerce" },
  { name: "Saint-Denis de la Réunion", type: "Tribunal mixte de commerce (DOM-TOM)" },
  { name: "Saint-Etienne", type: "Tribunal de commerce" },
  { name: "Saint-Malo", type: "Tribunal de commerce" },
  { name: "Saint-Nazaire", type: "Tribunal de commerce" },
  { name: "Saint-Omer", type: "Tribunal de commerce" },
  { name: "Saint-Pierre de la Réunion", type: "Tribunal mixte de commerce (DOM-TOM)" },
  { name: "Saint-Quentin", type: "Tribunal de commerce" },
  { name: "Saintes", type: "Tribunal de commerce" },
  { name: "Salon-de-Provence", type: "Tribunal de commerce" },
  { name: "Sarreguemines", type: "Tribunal judiciaire statuant commercialement (Alsace-Moselle)" },
  { name: "Saverne", type: "Tribunal judiciaire statuant commercialement (Alsace-Moselle)" },
  { name: "Sedan", type: "Tribunal de commerce" },
  { name: "Sens", type: "Tribunal de commerce" },
  { name: "Soissons", type: "Tribunal de commerce" },
  { name: "Strasbourg", type: "Tribunal judiciaire statuant commercialement (Alsace-Moselle)" },
  { name: "Tarbes", type: "Tribunal de commerce" },
  { name: "Tarascon", type: "Tribunal de commerce" },
  { name: "Thionville", type: "Tribunal judiciaire statuant commercialement (Alsace-Moselle)" },
  { name: "Thonon-les-Bains", type: "Tribunal de commerce" },
  { name: "Toulon", type: "Tribunal de commerce" },
  { name: "Toulouse", type: "Tribunal de commerce" },
  { name: "Tourcoing", type: "Tribunal de commerce" },
  { name: "Tours", type: "Tribunal de commerce" },
  { name: "Troyes", type: "Tribunal de commerce" },
  { name: "Valenciennes", type: "Tribunal de commerce" },
  { name: "Vannes", type: "Tribunal de commerce" },
  { name: "Versailles", type: "Tribunal de commerce" },
  { name: "Vesoul", type: "Tribunal de commerce" },
  { name: "Vienne", type: "Tribunal de commerce" },
  { name: "Villefranche-sur-Saône", type: "Tribunal de commerce" },
]
.filter((tribunal, index, self) =>
  index === self.findIndex((t) => t.name.trim().toLowerCase() === tribunal.name.trim().toLowerCase())
)
.sort((a, b) => a.name.localeCompare(b.name));